services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "rpsdb"
    ports:
      - 5432:5432
  app:
    build: .
    container_name: app
    image: app
    env_file:
      - .env
    environment:
      DB_URL: "postgres://postgresadmin:admin123@postgres:5432/rpsdb"
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - postgres

volumes:
  pg-data:
